# Generated by Django 3.2.9 on 2024-01-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
