# Generated by Django 3.2.9 on 2024-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_userportfolio_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfolio',
            old_name='published',
            new_name='is_free',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='without_login',
            field=models.BooleanField(default=False),
        ),
    ]
