# Generated by Django 3.2.9 on 2024-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20240125_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='./Images/'),
        ),
    ]
