# Generated by Django 3.2.9 on 2024-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_alter_userportfolio_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
