# Generated by Django 3.2.9 on 2024-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_userportfolio_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
