# Generated by Django 4.0.5 on 2024-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_auto_20240131_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=16)),
            ],
        ),
    ]
