# Generated by Django 4.0.5 on 2024-02-29 05:54

import datetime
from django.db import migrations, models
# from django.utils.timezone import utc
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_temptokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 2, 29, 5, 54, 55, 155174, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
