# Generated by Django 4.0.5 on 2024-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='show_ticker',
            field=models.BooleanField(default=False),
        ),
    ]
