from django.urls import path
from . import views
from django.shortcuts import redirect, reverse


urlpatterns = [
    path('',views.home),
    #path('daily', views.daily),
    #path('calc', views.calc),
    #path('total',views.total),
    #path('upload', views.upload),
    #path('graph', views.graph),
    path('predict_price', views.predict_price),
    #path('download_file', views.download_file),
    #path('upload_csv', views.upload_csv),
    #path('website_quote', views.website_quote),
    #path('most_active_options', views.most_active_options),
    #path('highest_implied_volatility', views.highest_implied_volatility),
    #path('exploding_IV', views.exploding_IV),
    #path('imploding_IV', views.imploding_IV),
    #path('option_volume_gainers', views.option_volume_gainers),
    #path('option_volume_losers', views.option_volume_losers),
    #path('option_open_interest_gainers', views.option_open_interest_gainers),
    #path('option_open_interest_losers', views.option_open_interest_losers),
    #path('website_market', views.webiste_market),
    #path('option_chain', views.option_chain),
    #path('option_chain_graph', views.option_chain_graph),
    #path('implied_volatility', views.implied_volatility),
    #path('volume', views.volume),
    #path('open_interest', views.open_interest),
    #path('get_files', views.get_files),
    path('predict_price_new', views.predict_price_new),
    path('predict_price_graph', views.predict_price_graph),
    path('predict_price_hv_graph', views.predict_price_hv_graph),
    path('screener_data', views.get_screener_api),
    path('screener_1', views.screener_1),
    path('screener_2', views.screener_2),
    path('screener_3', views.screener_3),
    path('screener_4', views.screener_4),
    path('relative_valuation', views.relative_valuation),
    path('relative_valuation_2', views.relative_valuation_2),
    path('rv_symbol', views.get_rv_symbol),
    path('get_company', views.get_company),
    path('get_company_2', views.get_company_2),
    path('get_industry_percentile', views.get_industry_percentile),
    #path('get_revenue_operating_netincome_data', views.view_revenue_operating_netincome_data),
    #path('technical_analysis_implied', views.technical_analysis_implied),
    #path('get_sales_beta_revenue_operating', views.view_sales_beta_revenue_operating),
    path('historical_relative_valuation', views.historical_relative_valuation),
    path('read_fcff', views.read_fcff),
    path('read_fcff_0', views.read_fcff_0),
    #path('checklist', views.checklist),
    #path('checklist_comapny', views.checklist_comapny),
    path('industry_report', views.industry_report),
    path('blogs', views.get_blog),
    path('macroeconomics', views.get_macroeconomics),
    path('get_blog_by_id', views.get_blog_by_id),
    path('get_all_blog', views.get_all_blog),
    path('get_quarters', views.get_quarters),
    path('get_quarters_0', views.get_quarters_0),
    #path('pro_version', views.pro_version),
    path('student_version', views.student_version),
    path('get_symbol_quarter', views.get_symbol_quarter),
    path('get_symbol_quarter_0', views.get_symbol_quarter_0),
    path('get_portfolio_symbols', views.get_portfolio_symbols),
    path('get_valuation_price', views.get_valuation_price),
    path('get_sector_industry', views.get_sector_industry),
    path('get_industry', views.get_industry),
]
